# Configuration for SSH Keys
# Format: "Label|User/Email|PublicKey"
KEYS=(
  "Personal|contact.mijanur80@gmail.com|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOhFnsZEj3hobSCHPKM5nBe5pe5JpMBZLkclhs/4tbsq contact.mijanur80@gmail.com"
  "Office Windows Key|azuread\mijanurrahman@DESKTOP-GU545GC|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJDr0NzVQIXILM0AN/Fq6sJQDzylZBteK4blpGvrYzOi azuread\mijanurrahman@DESKTOP-GU545GC"
  "iOS|root@localhost|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDIuCvdGaodeKgn9cRLndpx8s4uuJ9qV11bsHF4aJ1XF root@localhost"
)